version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build: ./client
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    depends_on:
      - server
    environment:
      - API_URI=http://server:3000/api/v1  

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
